---

- name: install packages (Debian)
  when: ansible_os_family == 'Debian'
  apt:
    name: gmetad
    state: present
  tags:
    - ganglia_metad_install
    - ganglia_metad
    - metad
    - install
    - ganglia

- name: install packages (RedHat)
  when: ansible_os_family == 'RedHat'
  yum:
    name: ganglia-gmetad
    state: present

- name: configure
  template:
    src: gmetad.conf.j2
    dest: /etc/ganglia/gmetad.conf
  tags:
    - ganglia_metad_configure
    - ganglia_metad
    - metad
    - configure
    - ganglia

- name: fix rrds permissions (RedHat)
  when: ansible_os_family == 'RedHat'
  file:
    path: /var/lib/ganglia/rrds
    state: directory
    owner: nobody
    group: nobody
    mode: 0755
    recurse: yes
  tags:
    - ganglia_metad_configure
    - ganglia_metad
    - metad
    - configure
    - ganglia


- name: restart gmetad
  service:
    name: gmetad
    state: restarted
  tags:
    - ganglia_metad_service
    - ganglia_metad
    - ganglia_service
    - ganglia
    - service
